# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cdad71e84308840e6c9735a2c94735c2543a56b687a02c5df1b1e969f275a3c6f4d27213f0ef4bd9bf094f15875f003ca676fe93d004c0ba50dfa483145f2db

test:
  secret_key_base: b35bf65ceede57763fd54d8ac6fed71050712a27d0a79992095c69eabdef11e8848cedeb40cceeaaf4812820a23634c4b9fa6121b3db59cf17579b457f79a04e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
